trigger:
- master

parameters:
  - name: useCache
    displayName: 'cache vcpkg artifacts?'
    type: boolean
    default: true
  - name: builds
    type: object
    default:
      - name: linux
        imageName: 'ubuntu-18.04'
        options:
          cmakeArgs: '-DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10'
      - name: mac
        imageName: macos-10.15
        options:
          cmakeArgs: '' # need to have some kind of options or our template breaks
      - name: windows
        imageName: 'vs2017-win2016'
        options:
          cmakeArgs: '-G "Visual Studio 15 2017 Win64"'
      - name: coverage
        imageName: 'ubuntu-18.04'
        options:
          collectCoverage: true
          buildType: Debug
          cmakeArgs: '-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DHUSTLE_CODE_COVERAGE=ON'
  - name: defaults
    type: object
    default:
      buildType: Release

jobs:
  - template: ci/build_jobs.yml
    parameters:
      builds: ${{ parameters.builds }}
      defaultOptions: ${{ parameters.defaults }}
