# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      extraCmakeArgs: '-DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10'
    mac:
      imageName: 'macos-10.14'
      extraCmakeArgs: ''

pool:
  vmImage: '$(imageName)'

steps:
- checkout: self
  submodules: true
- script: |
    mkdir build
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake $(extraCmakeArgs) ..
    make
  displayName: 'Build'
- script: |
    cd build
    mkdir package
    cpack -B package -G TGZ
  displayName: 'Package'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: build/package
    artifactName: test_artifact
- script: |
    cd build
    ctest
  displayName: 'Test'
