################################################################################
# Copyright (c) Devin Nakamura
# SPDX-License-Identifier: BSD-2-Clause
################################################################################

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      extraCmakeArgs: '-DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10'
    mac:
      imageName: 'macos-10.15'
      extraCmakeArgs: ''

pool:
  vmImage: '$(imageName)'

steps:
- checkout: self
  submodules: true
- script: |
    mkdir -p build/vcpkg_installed
  displayName: Create Dirs
- task: Cache@2
  inputs:
    key: 'vcpkg | "$(Agent.OS)" | vcpkg.json'
- script: |
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake $(extraCmakeArgs) ..
    make
  displayName: 'Build'
- script: |
    cd build
    ctest
  displayName: 'Test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: '**/*_test.xml'
