# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true
- script: |
    mkdir build
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 ..
    make
  displayName: 'Build'
- script: |
    cd build
    cpack -G TGZ
  displayName: 'Package'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: build/hustle-0.1.0-Linux.tar.gz
    artifactName: test_artifact
- script: |
    cd build
    ctest
  displayName: 'Test'
