trigger:
- debug

parameters:
  - name: useCache
    displayName: 'cache vcpkg artifacts?'
    type: boolean
    default: true
  - name: builds
    type: object
    default:
      - name: linux
        imageName: 'ubuntu-18.04'
        options:
          cmakeArgs: '-DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10'
      - name: coverage
        imageName: 'ubuntu-22.04'
        options:
          buildType: Debug
          cmakeArgs: '-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DHUSTLE_CODE_COVERAGE=ON'
        coverageBuild: true
  - name: defaults
    type: object
    default:
      buildType: Release
      uploadCoverage: false

jobs:
  - template: build_jobs.yml
    parameters:
      builds: ${{ parameters.builds }}
      defaultOptions: ${{ parameters.defaults }}
