trigger:
- debug

parameters:
  - name: useCache
    displayName: 'cache vcpkg artifacts?'
    type: boolean
    default: true
  - name: builds
    type: object
    default:
      - name: linux
        imageName: 'ubuntu-22.04'
        options:
          cmakeArgs: '' # need to have some kind of options or our template breaks
      #- name: mac
      #  imageName: macos-12
      #  options:
      #    cmakeArgs: '' # need to have some kind of options or our template breaks
      - name: windows
        imageName: 'windows-2022'
        options:
          cmakeArgs: '-G "Visual Studio 17 2022 Win64"'
      - name: coverage
        imageName: 'ubuntu-22.04'
        options:
          collectCoverage: true
          uploadCoverage: true
          buildType: Debug
          cmakeArgs: '-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DHUSTLE_CODE_COVERAGE=ON'
  - name: defaults
    type: object
    default:
      buildType: Release

jobs:
  - template: build_jobs.yml
    parameters:
      builds: ${{ parameters.builds }}
      defaultOptions: ${{ parameters.defaults }}
